name: Andreas Blog
description: Ramblings of a game developer
url: http://localhost:4000
markdown: kramdown
highlighter: rouge
safe: true
lsi: false
source: F:\Personal\Programming\GithubPage
paginate: 5